
import { LinkItem, Category } from './types';

export const CATEGORIES: Category[] = [
  { id: 'ia', name: 'Inteligência Artificial', icon: 'wand-magic-sparkles' },
  { id: 'jogo', name: 'Jogos e Entretenimento', icon: 'gamepad' },
  { id: 'streaming', name: 'Streaming e TV', icon: 'tv' },
  { id: 'social', name: 'Redes Sociais', icon: 'share-nodes' },
  { id: 'compra', name: 'Compras Online', icon: 'cart-shopping' },
  { id: 'outro', name: 'Utilidades e Hacks', icon: 'ellipsis' },
];

// LOCK: SEÇÃO PERMANENTE - PROIBIDO ALTERAR SEM PERMISSÃO
export const INITIAL_LINKS: LinkItem[] = [
  // --- CATEGORIA 1: IA ---
  { id: 'ia-gamma', name: 'Gamma', url: 'https://gamma.app', description: 'Criação de apresentações e documentos com IA.', category: 'ia', subCategory: 'IA', baseViews: 3421 },
  { id: 'ia-ideogram', name: 'Ideogram', url: 'https://ideogram.ai', description: 'Geração de imagens com foco em tipografia.', category: 'ia', subCategory: 'IA', baseViews: 1245 },
  { id: 'ia-suno', name: 'Suno AI', url: 'https://suno.ai', description: 'Criação de músicas completas com IA.', category: 'ia', subCategory: 'IA', baseViews: 890 },
  { id: 'ia-manus', name: 'Manus', url: 'https://manus.ai', description: 'Assistente de escrita e produtividade.', category: 'ia', subCategory: 'IA', baseViews: 560 },
  { id: 'ia-leonardo', name: 'Leonardo AI', url: 'https://leonardo.ai', description: 'Geração de imagens e assets de alta qualidade.', category: 'ia', subCategory: 'IA', baseViews: 2134 },
  { id: 'ia-chatgpt', name: 'ChatGPT', url: 'https://chat.openai.com', description: 'Modelo de linguagem líder para conversação.', category: 'ia', subCategory: 'IA', baseViews: 5671 },
  { id: 'ia-luzia', name: 'LuzIA', url: 'https://www.luzia.com', description: 'IA para WhatsApp e Telegram.', category: 'ia', subCategory: 'IA', baseViews: 3210 },
  { id: 'ia-monica', name: 'Monica', url: 'https://monica.im', description: 'Copiloto de IA para produtividade.', category: 'ia', subCategory: 'IA', baseViews: 920 },
  { id: 'ia-lovable', name: 'Lovable', url: 'https://lovable.so', description: 'Criação de sites e apps com IA.', category: 'ia', subCategory: 'IA', baseViews: 450 },
  { id: 'ia-roboneo', name: 'RoboNeo', url: 'https://roboneo.ai', description: 'Automação inteligente.', category: 'ia', subCategory: 'IA', baseViews: 310 },
  { id: 'ia-ebookmaker', name: 'Ebookmaker', url: 'https://ebookmaker.ai', description: 'Criação automática de eBooks.', category: 'ia', subCategory: 'IA', baseViews: 280 },
  { id: 'ia-deepseek', name: 'DeepSeek', url: 'https://www.deepseek.com', description: 'Modelo de linguagem de alto desempenho.', category: 'ia', subCategory: 'IA', baseViews: 1540 },
  { id: 'ia-notebooklm', name: 'NotebookLM', url: 'https://notebooklm.google', description: 'IA de pesquisa e análise do Google.', category: 'ia', subCategory: 'IA', baseViews: 780 },
  { id: 'ia-imagineart', name: 'ImagineArt', url: 'https://www.imagine.art', description: 'Criação artística com IA.', category: 'ia', subCategory: 'IA', baseViews: 640 },
  { id: 'ia-nanobanana', name: 'Nano Banana', url: 'https://nanobananas.ai', description: 'Exploração de modelos leves de IA.', category: 'ia', subCategory: 'IA', baseViews: 520 },
  { id: 'ia-veo3', name: 'Veo 3', url: 'https://deepmind.google/technologies/veo', description: 'Geração de vídeo de alta fidelidade do Google.', category: 'ia', subCategory: 'IA', baseViews: 890 },
  { id: 'ia-flux', name: 'Flux', url: 'https://flux.ai', description: 'Design de hardware e esquemas com IA.', category: 'ia', subCategory: 'IA', baseViews: 410 },
  { id: 'ia-deepseekchat', name: 'DeepSeek Chat', url: 'https://chat.deepseek.com', description: 'Interface de chat do DeepSeek.', category: 'ia', subCategory: 'IA', baseViews: 1100 },
  { id: 'ia-vidguru', name: 'Vidguru', url: 'https://www.vidguru.ai', description: 'Edição de vídeo inteligente.', category: 'ia', subCategory: 'IA', baseViews: 340 },
  { id: 'ia-transkriptor', name: 'Transkriptor', url: 'https://transkriptor.com', description: 'Transcrição de áudio em texto.', category: 'ia', subCategory: 'IA', baseViews: 670 },
  { id: 'ia-scholarai', name: 'ScholarAI', url: 'https://www.scholarai.io', description: 'IA para pesquisadores acadêmicos.', category: 'ia', subCategory: 'IA', baseViews: 560 },
  { id: 'ia-researchrabbit', name: 'Research Rabbit', url: 'https://www.researchrabbit.ai', description: 'Mapeamento de literatura acadêmica.', category: 'ia', subCategory: 'IA', baseViews: 490 },
  { id: 'ia-grammarly', name: 'Grammarly', url: 'https://www.grammarly.com', description: 'Assistente de escrita e gramática.', category: 'ia', subCategory: 'IA', baseViews: 3400 },
  { id: 'ia-notionai', name: 'Notion AI', url: 'https://www.notion.so/product/ai', description: 'Escrita e organização dentro do Notion.', category: 'ia', subCategory: 'IA', baseViews: 2100 },
  { id: 'ia-trelloai', name: 'Trello IA', url: 'https://trello.com', description: 'Automação de quadros no Trello.', category: 'ia', subCategory: 'IA', baseViews: 890 },
  { id: 'ia-consensus', name: 'Consensus', url: 'https://consensus.app', description: 'Motor de busca baseado em ciência.', category: 'ia', subCategory: 'IA', baseViews: 450 },
  { id: 'ia-canva', name: 'Canva', url: 'https://www.canva.com', description: 'Design facilitado com ferramentas de IA.', category: 'ia', subCategory: 'IA', baseViews: 4800 },
  { id: 'ia-synthesia', name: 'Synthesia', url: 'https://www.synthesia.io', description: 'Geração de vídeos com avatares de IA.', category: 'ia', subCategory: 'IA', baseViews: 730 },
  { id: 'ia-elevenlabs', name: 'ElevenLabs', url: 'https://elevenlabs.io', description: 'A melhor voz de IA do mundo.', category: 'ia', subCategory: 'IA', baseViews: 2900 },
  { id: 'ia-typecast', name: 'Typecast', url: 'https://typecast.ai', description: 'Dublagem e vozes realistas.', category: 'ia', subCategory: 'IA', baseViews: 320 },
  { id: 'ia-mendeley', name: 'Mendeley', url: 'https://www.mendeley.com', description: 'Gerenciador de referências.', category: 'ia', subCategory: 'IA', baseViews: 800 },
  { id: 'ia-replitai', name: 'Replit AI', url: 'https://replit.com', description: 'Codificação assistida por IA.', category: 'ia', subCategory: 'IA', baseViews: 1200 },
  { id: 'ia-copilot', name: 'GitHub Copilot', url: 'https://github.com/features/copilot', description: 'O par programador de IA.', category: 'ia', subCategory: 'IA', baseViews: 3100 },
  { id: 'ia-dungeon', name: 'AI Dungeon', url: 'https://play.aidungeon.com', description: 'RPG de aventura infinita.', category: 'ia', subCategory: 'IA', baseViews: 670 },
  { id: 'ia-wonder', name: 'Wonder', url: 'https://www.artbreeder.com', description: 'Criação de personagens e arte.', category: 'ia', subCategory: 'IA', baseViews: 540 },
  { id: 'ia-sudowrite', name: 'Sudowrite', url: 'https://www.sudowrite.com', description: 'IA para escritores de ficção.', category: 'ia', subCategory: 'IA', baseViews: 430 },
  { id: 'ia-faceapp', name: 'FaceApp', url: 'https://www.faceapp.com', description: 'Edição de rosto foto-realista.', category: 'ia', subCategory: 'IA', baseViews: 1200 },
  { id: 'ia-toongineer', name: 'Toongineer', url: 'https://toongineer.com', description: 'Transforme fotos em desenhos animados.', category: 'ia', subCategory: 'IA', baseViews: 310 },
  { id: 'ia-meme', name: 'AI Meme Generator', url: 'https://imgflip.com/ai-meme', description: 'Crie memes instantâneos com IA.', category: 'ia', subCategory: 'IA', baseViews: 890 },
  { id: 'ia-quillbot', name: 'QuillBot', url: 'https://quillbot.com', description: 'Parafraseador e resumidor.', category: 'ia', subCategory: 'IA', baseViews: 2300 },
  { id: 'ia-n8n', name: 'N8N', url: 'https://n8n.io', description: 'Automação de fluxo de trabalho.', category: 'ia', subCategory: 'IA', baseViews: 450 },
  { id: 'ia-base44', name: 'Base 44', url: 'https://base44.com', description: 'Ferramentas de IA avançadas.', category: 'ia', subCategory: 'IA', baseViews: 210 },
  { id: 'ia-heyboss', name: 'Hey Boss AI', url: 'https://heyboss.ai', description: 'Assistente corporativo.', category: 'ia', subCategory: 'IA', baseViews: 180 },
  { id: 'ia-aistudio', name: 'Google AI Studio', url: 'https://aistudio.google.com', description: 'Desenvolvimento rápido com Gemini.', category: 'ia', subCategory: 'IA', baseViews: 3400 },
  { id: 'ia-mgx', name: 'MGX', url: 'https://tinyurl.com/mtajx5zb', description: 'Plataforma de IA experimental.', category: 'ia', subCategory: 'IA', baseViews: 290 },
  { id: 'ia-maestro', name: 'Maestro IA', url: 'https://maestrohub.site/', description: 'Hub de projetos e letras para Suno.', category: 'ia', subCategory: 'IA', baseViews: 1489 },
  { id: 'ia-nemo', name: 'Nemo Video', url: 'https://www.nemovideo.com', description: 'Geração de vídeos rápida.', category: 'ia', subCategory: 'IA', baseViews: 240 },
  { id: 'ia-readdy', name: 'Readdy AI', url: 'https://readdy.ai', description: 'Preparação para produtividade.', category: 'ia', subCategory: 'IA', baseViews: 310 },

  // --- CATEGORIA 2: JOGOS (60+ LINKS) ---
  { id: 'j-lichess', name: 'Lichess', url: 'https://lichess.org', description: 'Xadrez online gratuito.', category: 'jogo', subCategory: 'ESTRATÉGIA', baseViews: 1432 },
  { id: 'j-2048', name: '2048', url: 'https://play2048.co', description: 'O clássico jogo de lógica numérica.', category: 'jogo', subCategory: 'LÓGICA', baseViews: 890 },
  { id: 'j-sudoku', name: 'Sudoku', url: 'https://sudoku.com', description: 'Desafios diários de Sudoku.', category: 'jogo', subCategory: 'LÓGICA', baseViews: 760 },
  { id: 'j-alchemy2', name: 'Little Alchemy 2', url: 'https://littlealchemy2.com', description: 'Misture elementos.', category: 'jogo', subCategory: 'ESTRATÉGIA', baseViews: 540 },
  { id: 'j-minesweeper', name: 'Minesweeper Online', url: 'https://minesweeper.online', description: 'Campo minado clássico online.', category: 'jogo', subCategory: 'LÓGICA', baseViews: 430 },
  { id: 'j-agar', name: 'Agar.io', url: 'https://agar.io', description: 'Coma células menores.', category: 'jogo', subCategory: 'MULTIPLAYER', baseViews: 2100 },
  { id: 'j-slither', name: 'Slither.io', url: 'https://slither.io', description: 'Cresça o máximo possível.', category: 'jogo', subCategory: 'MULTIPLAYER', baseViews: 1800 },
  { id: 'j-diep', name: 'Diep.io', url: 'https://diep.io', description: 'Tanques multiplayer.', category: 'jogo', subCategory: 'MULTIPLAYER', baseViews: 920 },
  { id: 'j-krunker', name: 'Krunker.io', url: 'https://krunker.io', description: 'FPS rápido no navegador.', category: 'jogo', subCategory: 'MULTIPLAYER', baseViews: 1543 },
  { id: 'j-shell', name: 'Shell Shockers', url: 'https://shellshock.io', description: 'FPS de ovos.', category: 'jogo', subCategory: 'MULTIPLAYER', baseViews: 870 },
  { id: 'j-paper2', name: 'Paper.io 2', url: 'https://paper-io.com', description: 'Conquiste territórios.', category: 'jogo', subCategory: 'CASUAL', baseViews: 1200 },
  { id: 'j-hole', name: 'Hole.io', url: 'https://hole-io.com', description: 'Seja o maior buraco negro.', category: 'jogo', subCategory: 'CASUAL', baseViews: 940 },
  { id: 'j-wheels', name: 'Happy Wheels', url: 'https://www.totaljerkface.com/happy_wheels.php', description: 'Física maluca.', category: 'jogo', subCategory: 'CASUAL', baseViews: 650 },
  { id: 'j-moto', name: 'Moto X3M', url: 'https://www.y8.com/games/moto_x3m', description: 'Corrida de moto.', category: 'jogo', subCategory: 'CASUAL', baseViews: 1100 },
  { id: 'j-crossy', name: 'Crossy Road', url: 'https://crossyroad.com/play', description: 'Atravesse a rua.', category: 'jogo', subCategory: 'CASUAL', baseViews: 1400 },
  { id: 'j-bullet', name: 'Bullet Force', url: 'https://bulletforce.com', description: 'FPS realista.', category: 'jogo', subCategory: 'AÇÃO', baseViews: 890 },
  { id: 'j-forward', name: 'Forward Assault', url: 'https://krunker.io/game/forward-assault-remix', description: 'Ação tática FPS.', category: 'jogo', subCategory: 'FPS', baseViews: 650 },
  { id: 'j-masked', name: 'Masked Forces', url: 'https://masked-forces.com', description: 'Combate FPS intenso.', category: 'jogo', subCategory: 'AÇÃO', baseViews: 420 },
  { id: 'j-zombs', name: 'Zombs Royale', url: 'https://zombsroyale.io', description: 'Battle Royale 2D.', category: 'jogo', subCategory: 'AÇÃO', baseViews: 760 },
  { id: 'j-warbrokers', name: 'War Brokers', url: 'https://warbrokers.io', description: 'FPS com veículos.', category: 'jogo', subCategory: 'AÇÃO', baseViews: 540 },
  { id: 'j-realm', name: 'Realm of the Mad God', url: 'https://www.realmofthemadgod.com', description: 'MMORPG bullet-hell cooperativo.', category: 'jogo', subCategory: 'RPG', baseViews: 430 },
  { id: 'j-adventure', name: 'AdventureQuest Worlds', url: 'https://www.aq.com', description: 'RPG clássico de turnos.', category: 'jogo', subCategory: 'AVENTURA', baseViews: 310 },
  { id: 'j-darkorbit', name: 'DarkOrbit Reloaded', url: 'https://www.darkorbit.com', description: 'Batalhas espaciais épicas.', category: 'jogo', subCategory: 'RPG', baseViews: 1200 },
  { id: 'j-flyff', name: 'Flyff Universe', url: 'https://www.flyffuniverse.com', description: 'MMORPG no navegador.', category: 'jogo', subCategory: 'RPG', baseViews: 850 },
  { id: 'j-eternalfury', name: 'Eternal Fury', url: 'https://eternalfury2.com', description: 'RPG de estratégia.', category: 'jogo', subCategory: 'AVENTURA', baseViews: 410 },
  { id: 'j-madalin', name: 'Madalin Stunt Cars 2', url: 'https://www.crazygames.com/game/madalin-stunt-cars-2', description: 'Acrobacias com carros.', category: 'jogo', subCategory: 'CORRIDA', baseViews: 1500 },
  { id: 'j-drift', name: 'Drift Hunters', url: 'https://www.crazygames.com/game/drift-hunters', description: 'Simulador de drift.', category: 'jogo', subCategory: 'CORRIDA', baseViews: 1300 },
  { id: 'j-8ball', name: '8 Ball Pool', url: 'https://www.miniclip.com/games/8-ball-pool', description: 'Sinuca online.', category: 'jogo', subCategory: 'ESPORTES', baseViews: 5400 },
  { id: 'j-basketball', name: 'Basketball Stars', url: 'https://www.crazygames.com/game/basketball-stars', description: 'Basquete 1x1.', category: 'jogo', subCategory: 'ESPORTES', baseViews: 980 },
  { id: 'j-soccer', name: 'Soccer Random', url: 'https://www.crazygames.com/game/soccer-random', description: 'Futebol caótico.', category: 'jogo', subCategory: 'ESPORTES', baseViews: 1100 },
  { id: 'js-poki', name: 'Poki', url: 'https://poki.com', description: 'Playground de jogos.', category: 'jogo', subCategory: 'GERAL', baseViews: 4500 },
  { id: 'js-crazy', name: 'CrazyGames', url: 'https://www.crazygames.com', description: 'Melhores jogos grátis.', category: 'jogo', subCategory: 'GERAL', baseViews: 3200 },
  { id: 'js-y8', name: 'Y8 Games', url: 'https://www.y8.com', description: 'Jogos Flash e HTML5.', category: 'jogo', subCategory: 'GERAL', baseViews: 2100 },
  { id: 'js-miniclip', name: 'Miniclip', url: 'https://www.miniclip.com', description: 'Ação e Esportes.', category: 'jogo', subCategory: 'GERAL', baseViews: 1900 },
  { id: 'js-itch', name: 'Itch.io', url: 'https://itch.io/games/platform-web', description: 'Indie Games.', category: 'jogo', subCategory: 'GERAL', baseViews: 1500 },
  { id: 'js-agame', name: 'Agame', url: 'https://www.agame.com', description: 'Jogos online para todos.', category: 'jogo', subCategory: 'GERAL', baseViews: 890 },
  { id: 'js-kongregate', name: 'Kongregate', url: 'https://www.kongregate.com', description: 'Milhares de jogos indie.', category: 'jogo', subCategory: 'GERAL', baseViews: 1200 },
  { id: 'js-friv', name: 'Friv', url: 'https://www.friv.com', description: 'Clássico site de jogos.', category: 'jogo', subCategory: 'GERAL', baseViews: 2800 },
  { id: 'js-crazybr', name: 'CrazyGames BR', url: 'https://www.crazygames.com.br', description: 'Versão brasileira do CrazyGames.', category: 'jogo', subCategory: 'GERAL', baseViews: 1400 },
  { id: 'js-addicting', name: 'Addicting Games', url: 'https://www.addictinggames.com', description: 'Jogos viciantes desde sempre.', category: 'jogo', subCategory: 'GERAL', baseViews: 920 },
  { id: 'js-gameflare', name: 'Gameflare', url: 'https://www.gameflare.com', description: 'Jogos 3D de alta qualidade.', category: 'jogo', subCategory: 'GERAL', baseViews: 650 },
  { id: 'js-armor', name: 'Armor Games', url: 'https://www.armorgames.com', description: 'Aventura e estratégia.', category: 'jogo', subCategory: 'GERAL', baseViews: 870 },
  { id: 'js-playgames', name: 'Play-Games', url: 'https://www.play-games.com', description: 'Diversão garantida.', category: 'jogo', subCategory: 'GERAL', baseViews: 540 },
  { id: 'js-coolmath', name: 'CoolMathGames', url: 'https://www.coolmathgames.com', description: 'Jogos de lógica e matemática.', category: 'jogo', subCategory: 'GERAL', baseViews: 3200 },
  { id: 'js-funny', name: 'FunnyGames', url: 'https://www.funnygames.org', description: 'Milhares de jogos divertidos.', category: 'jogo', subCategory: 'GERAL', baseViews: 410 },
  { id: 'js-silver', name: 'SilverGames', url: 'https://www.silvergames.com', description: 'Jogos rápidos e leves.', category: 'jogo', subCategory: 'GERAL', baseViews: 340 },
  { id: 'js-freegames', name: 'FreeGames.org', url: 'https://www.freegames.org', description: 'Jogos 100% grátis.', category: 'jogo', subCategory: 'GERAL', baseViews: 210 },
  { id: 'js-paco', name: 'PacoGames', url: 'https://www.pacogames.com', description: 'Líder em jogos MMO e FPS.', category: 'jogo', subCategory: 'GERAL', baseViews: 670 },
  { id: 'js-gamepix', name: 'GamePix', url: 'https://www.gamepix.com', description: 'Catálogo moderno de jogos HTML5.', category: 'jogo', subCategory: 'GERAL', baseViews: 840 },
  { id: 'js-jogos360', name: 'Jogos 360', url: 'https://www.jogos360.com.br', description: 'O melhor site brasileiro de jogos.', category: 'jogo', subCategory: 'GERAL', baseViews: 5400 },
  { id: 'js-clickjogos', name: 'Click Jogos', url: 'https://www.clickjogos.com.br', description: 'Clássico absoluto nacional.', category: 'jogo', subCategory: 'GERAL', baseViews: 4800 },
  { id: 'js-onlinegratis', name: 'Jogos Online Grátis', url: 'https://www.jogosonlinegratis.com.br', description: 'Diversão para toda a família.', category: 'jogo', subCategory: 'GERAL', baseViews: 1200 },
  { id: 'js-playhop', name: 'Playhop', url: 'https://www.playhop.com', description: 'Jogue sem baixar nada.', category: 'jogo', subCategory: 'GERAL', baseViews: 980 },
  { id: 'js-jogosfriv', name: 'Jogos Friv', url: 'https://www.jogosfriv.com', description: 'Especialista em jogos simples.', category: 'jogo', subCategory: 'GERAL', baseViews: 760 },
  { id: 'js-topjogos', name: 'Top Jogos', url: 'https://www.topjogos.com.br', description: 'Os melhores do momento.', category: 'jogo', subCategory: 'GERAL', baseViews: 540 },
  { id: 'js-retro', name: 'RetroGames.cc', url: 'https://www.retrogames.cc', description: 'Emulador online de clássicos.', category: 'jogo', subCategory: 'GERAL', baseViews: 3100 },
  { id: 'js-classic', name: 'Classic Games Arcade', url: 'https://www.classicgamesarcade.com', description: 'Arcade dos anos 80 e 90.', category: 'jogo', subCategory: 'GERAL', baseViews: 1200 },
  { id: 'js-html5', name: 'HTML5 Games', url: 'https://www.html5games.com', description: 'Futuro dos jogos no browser.', category: 'jogo', subCategory: 'GERAL', baseViews: 1400 },
  { id: 'js-distribution', name: 'Game Distribution', url: 'https://www.gamedistribution.com', description: 'Portal para desenvolvedores e jogadores.', category: 'jogo', subCategory: 'GERAL', baseViews: 890 },
  { id: 'js-puzzle', name: 'Puzzle Prime', url: 'https://www.puzzleprime.com', description: 'O melhor para fãs de quebra-cabeça.', category: 'jogo', subCategory: 'GERAL', baseViews: 450 },

  // --- CATEGORIA 3: STREAMING ---
  { id: 'st-temp', name: 'Temp Mail', url: 'https://temp-mail.org', description: 'E-mails temporários para cadastros.', category: 'streaming', subCategory: 'UTILITÁRIO APOIO', baseViews: 4120 },
  { id: 'st-globo', name: 'Globoplay', url: 'https://globoplay.globo.com', description: 'A maior plataforma de streaming nacional.', category: 'streaming', subCategory: 'NACIONAL', baseViews: 3450 },
  { id: 'st-pluto', name: 'Pluto TV', url: 'https://pluto.tv', description: 'Canais de TV grátis e filmes.', category: 'streaming', subCategory: '100% GRÁTIS', baseViews: 2300 },
  { id: 'st-vix', name: 'VIX Cine e TV', url: 'https://www.vix.com/pt-br', description: 'Streaming gratuito de filmes e séries.', category: 'streaming', subCategory: '100% GRÁTIS', baseViews: 890 },
  { id: 'st-netmovies', name: 'NetMovies', url: 'https://www.netmovies.com.br', description: 'Filmes clássicos e novos gratuitos.', category: 'streaming', subCategory: 'FILMES GRÁTIS', baseViews: 1100 },
  { id: 'st-plus-sbt', name: '+SBT', url: 'https://www.sbt.com.br/mais-sbt', description: 'Todo o conteúdo do SBT online.', category: 'streaming', subCategory: 'TV GRÁTIS', baseViews: 1200 },
  { id: 'st-band', name: 'BandPlay', url: 'https://www.bandplay.com', description: 'Acesse a programação da Band.', category: 'streaming', subCategory: 'TV GRÁTIS', baseViews: 950 },
  { id: 'st-spcine', name: 'Spcine Play', url: 'https://www.spcineplay.com.br', description: 'Filmes brasileiros e internacionais.', category: 'streaming', subCategory: 'ACERVO CULTURAL', baseViews: 420 },
  { id: 'st-itau', name: 'Itaú Cultural Play', url: 'https://www.itauculturalplay.com.br', description: 'Cultura e cinema brasileiro.', category: 'streaming', subCategory: 'ACERVO CULTURAL', baseViews: 380 },
  { id: 'st-crunchy', name: 'Crunchyroll', url: 'https://www.crunchyroll.com', description: 'A maior biblioteca de animes.', category: 'streaming', subCategory: 'ANIMES', baseViews: 3543 },
  { id: 'st-plex', name: 'Plex', url: 'https://www.plex.tv/watch-free', description: 'Streaming de filmes e TV gratuito.', category: 'streaming', subCategory: 'FILMES & TV', baseViews: 1500 },
  { id: 'st-rakuten-tv', name: 'Rakuten TV', url: 'https://rakuten.tv/br', description: 'Cinema em casa.', category: 'streaming', subCategory: 'FILMES ONLINE', baseViews: 670 },
  { id: 'st-viki', name: 'Rakuten Viki', url: 'https://www.viki.com', description: 'Doramas e produções asiáticas.', category: 'streaming', subCategory: 'DORAMAS', baseViews: 1800 },
  { id: 'st-yt-movies', name: 'YouTube Filmes', url: 'https://www.youtube.com/feed/storefront', description: 'Filmes para alugar ou gratuitos.', category: 'streaming', subCategory: 'OFICIAL', baseViews: 2100 },
  { id: 'st-archive', name: 'Internet Archive', url: 'https://archive.org/details/movies', description: 'Domínio público e clássicos.', category: 'streaming', subCategory: 'CLÁSSICOS', baseViews: 3100 },
  { id: 'st-redbull', name: 'Red Bull TV', url: 'https://www.redbull.com/br-pt', description: 'Esportes de ação e aventura.', category: 'streaming', subCategory: 'ESPORTES', baseViews: 890 },

  // --- CATEGORIA 4: REDES SOCIAIS ---
  { id: 'soc-yt', name: 'YouTube', url: 'https://www.youtube.com', description: 'Vídeos, música e lives.', category: 'social', subCategory: 'VÍDEOS', baseViews: 9821 },
  { id: 'soc-reddit', name: 'Reddit', url: 'https://www.reddit.com', description: 'A primeira página da internet.', category: 'social', subCategory: 'COMUNIDADE', baseViews: 2984 },
  { id: 'soc-discord', name: 'Discord', url: 'https://discord.com', description: 'Lugar de conversa para gamers.', category: 'social', subCategory: 'CONVERSAS', baseViews: 5821 },
  { id: 'soc-x', name: 'X (Twitter)', url: 'https://x.com', description: 'O que está acontecendo agora.', category: 'social', subCategory: 'NOTÍCIAS', baseViews: 4100 },
  { id: 'soc-fb', name: 'Facebook', url: 'https://www.facebook.com', description: 'Conecte-se com amigos.', category: 'social', subCategory: 'SOCIAL', baseViews: 3200 },
  { id: 'soc-ig', name: 'Instagram', url: 'https://www.instagram.com', description: 'Compartilhe seus momentos.', category: 'social', subCategory: 'FOTOS/REELS', baseViews: 6291 },
  { id: 'soc-tiktok', name: 'TikTok', url: 'https://www.tiktok.com', description: 'Vídeos curtos virais.', category: 'social', subCategory: 'VÍDEOS CURTOS', baseViews: 7672 },
  { id: 'soc-twitch', name: 'Twitch', url: 'https://www.twitch.tv', description: 'Transmissões ao vivo de jogos.', category: 'social', subCategory: 'LIVES', baseViews: 4500 },
  { id: 'soc-spotify', name: 'Spotify', url: 'https://www.spotify.com', description: 'Música e podcasts ilimitados.', category: 'social', subCategory: 'MÚSICA', baseViews: 5200 },

  // --- CATEGORIA 5: COMPRAS ---
  { id: 'cp-amazon', name: 'Amazon Brasil', url: 'https://www.amazon.com.br', description: 'Loja global com entrega rápida.', category: 'compra', subCategory: 'GLOBAL', baseViews: 4741 },
  { id: 'cp-mercado', name: 'Mercado Livre', url: 'https://www.mercadolivre.com.br', description: 'Líder em e-commerce na América Latina.', category: 'compra', subCategory: 'LÍDER BR', baseViews: 5103 },
  { id: 'cp-shopee', name: 'Shopee Brasil', url: 'https://shopee.com.br', description: 'Ofertass com frete grátis.', category: 'compra', subCategory: 'OFERTAS', baseViews: 6542 },
  { id: 'cp-aliexpress', name: 'AliExpress', url: 'https://www.aliexpress.com', description: 'Produtos importados direto da China.', category: 'compra', subCategory: 'IMPORTADOS', baseViews: 4200 },
  { id: 'cp-magalu', name: 'Magazine Luiza', url: 'https://www.magazineluiza.com.br', description: 'Grande varejista brasileiro.', category: 'compra', subCategory: 'VAREJO', baseViews: 3100 },
  { id: 'cp-americanas', name: 'Americanas', url: 'https://www.americanas.com.br', description: 'Tudo o que você precisa.', category: 'compra', subCategory: 'VAREJO', baseViews: 2800 },
  { id: 'cp-casasbahia', name: 'Casas Bahia', url: 'https://www.casasbahia.com.br', description: 'Dedicação total a você.', category: 'compra', subCategory: 'VAREJO', baseViews: 1900 },
  { id: 'cp-extra', name: 'Extra', url: 'https://www.extra.com.br', description: 'Supermercado e eletrônicos.', category: 'compra', subCategory: 'SUPERMERCADO', baseViews: 850 },
  { id: 'cp-carrefour', name: 'Carrefour', url: 'https://www.carrefour.com.br', description: 'Rede global de supermercados.', category: 'compra', subCategory: 'SUPERMERCADO', baseViews: 920 },
  { id: 'cp-fastshop', name: 'Fast Shop', url: 'https://www.fastshop.com.br', description: 'Eletrônicos e eletrodomésticos premium.', category: 'compra', subCategory: 'PREMIUM', baseViews: 450 },
  { id: 'cp-havan', name: 'Havan', url: 'https://www.havan.com.br', description: 'Loja de departamentos completa.', category: 'compra', subCategory: 'DEPARTAMENTOS', baseViews: 1200 },
  { id: 'cp-kabum', name: 'KaBuM!', url: 'https://www.kabum.com.br', description: 'Tecnologia e Hardware gamer.', category: 'compra', subCategory: 'GAMER/TECH', baseViews: 3400 },
  { id: 'cp-pichau', name: 'Pichau', url: 'https://www.pichau.com.br', description: 'Hardware e PCs gamer.', category: 'compra', subCategory: 'GAMER/TECH', baseViews: 2100 },
  { id: 'cp-terabyte', name: 'Terabyte Shop', url: 'https://www.terabyteshop.com.br', description: 'A melhor loja gamer do Brasil.', category: 'compra', subCategory: 'GAMER/TECH', baseViews: 1800 },
  { id: 'cp-nike', name: 'Nike Brasil', url: 'https://www.nike.com.br', description: 'Artigos esportivos oficiais Nike.', category: 'compra', subCategory: 'ESPORTE', baseViews: 1540 },
  { id: 'cp-adidas', name: 'Adidas Brasil', url: 'https://www.adidas.com.br', description: 'Artigos esportivos oficiais Adidas.', category: 'compra', subCategory: 'ESPORTE', baseViews: 1200 },
  { id: 'cp-decathlon', name: 'Decathlon', url: 'https://www.decathlon.com.br', description: 'Tudo para o seu esporte.', category: 'compra', subCategory: 'ESPORTE', baseViews: 890 },
  { id: 'cp-renner', name: 'Renner', url: 'https://www.lojasrenner.com.br', description: 'Moda feminina, masculina e infantil.', category: 'compra', subCategory: 'MODA', baseViews: 1100 },
  { id: 'cp-cea', name: 'C&A', url: 'https://www.cea.com.br', description: 'Tendências de moda acessível.', category: 'compra', subCategory: 'MODA', baseViews: 950 },
  { id: 'cp-riachuelo', name: 'Riachuelo', url: 'https://www.riachuelo.com.br', description: 'Moda e casa.', category: 'compra', subCategory: 'MODA', baseViews: 870 },
  { id: 'cp-samsung', name: 'Samsung Brasil', url: 'https://www.samsung.com/br', description: 'Smartphones e eletrônicos Samsung.', category: 'compra', subCategory: 'ELETRÔNICOS', baseViews: 2500 },
  { id: 'cp-apple', name: 'Apple Brasil', url: 'https://www.apple.com/br', description: 'Produtos oficiais Apple no Brasil.', category: 'compra', subCategory: 'PREMIUM', baseViews: 3100 },
  { id: 'cp-motorola', name: 'Motorola Brasil', url: 'https://www.motorola.com.br', description: 'Smartphones oficiais Motorola.', category: 'compra', subCategory: 'SMARTPHONES', baseViews: 1100 },
  { id: 'cp-olx', name: 'OLX', url: 'https://www.olx.com.br', description: 'Compre e venda usados perto de você.', category: 'compra', subCategory: 'DESAPEGO', baseViews: 4500 },
  { id: 'cp-enjoei', name: 'Enjoei', url: 'https://www.enjoei.com.br', description: 'Brechó online e moda usada.', category: 'compra', subCategory: 'MODA USADA', baseViews: 2300 },

  // --- CATEGORIA 6: UTILIDADES (ORDEM ATUALIZADA) ---
  { id: 'ut-alphacoders', name: 'AlphaCoders 8K', url: 'https://alphacoders.com/popular-8k-wallpapers', description: 'Melhor acervo de wallpapers em 8K.', category: 'outro', subCategory: 'WALLPAPER 8K', baseViews: 3100 },
  { id: 'ut-wallhaven', name: 'Wallhaven Top', url: 'https://wallhaven.cc/toplist?page=50', description: 'A elite da arte digital e wallpapers.', category: 'outro', subCategory: 'ARTE DIGITAL', baseViews: 4500 },
  { id: 'ut-artstation', name: 'ArtStation Wallpapers', url: 'https://www.artstation.com/search?q=wallpaper', description: 'Wallpapers criados por profissionais.', category: 'outro', subCategory: 'CONCEPT ART', baseViews: 1800 },
  { id: 'ut-access', name: 'WallpaperAccess', url: 'https://wallpaperaccess.com', description: 'Coleções temáticas e variadas.', category: 'outro', subCategory: 'COLEÇÕES', baseViews: 1200 },
  { id: 'ut-zedge', name: 'Zedge', url: 'https://www.zedge.net/wallpapers', description: 'O maior portal de personalização mobile.', category: 'outro', subCategory: 'MOBILE FOCUS', baseViews: 6700 },
  { id: 'ut-pinterest', name: 'Pinterest Wallpapers', url: 'https://www.pinterest.com/search/pins/?q=wallpaper', description: 'Inspiração infinita para sua tela.', category: 'outro', subCategory: 'INSPIRAÇÃO', baseViews: 9800 },
  { id: 'ut-wallhere', name: 'WallHere', url: 'https://wallhere.com', description: 'Wallpapers em alta resolução para PC.', category: 'outro', subCategory: 'ALTA RESOLUÇÃO', baseViews: 920 },
  { id: 'ut-nexus', name: 'DesktopNexus', url: 'https://www.desktopnexus.com', description: 'Comunidade clássica de wallpapers.', category: 'outro', subCategory: 'COMUNIDADE', baseViews: 540 },
  { id: 'ot-gemini', name: 'Gemini', url: 'https://gemini.google.com', description: 'IA avançada do Google para tudo.', category: 'outro', subCategory: 'IA GOOGLE', baseViews: 9432 },
  { id: 'ot-cmsp', name: 'Hack CMSP', url: 'https://cmsphacks.xyz/', description: 'Ferramentas utilitárias para CMSP.', category: 'outro', subCategory: 'ESTUDOS/HACK', baseViews: 3121 },
  { id: 'ot-subway', name: 'Hack Subway Surf', url: 'https://youtu.be/nvA0fISMfus?si=M0ou9x0-6EszvGB2', description: 'Aprenda a instalar o mod no vídeo.', category: 'outro', subCategory: 'GAME MOD/VÍDEO', baseViews: 12437 },
];
